///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("b0ec60bc-8556-407f-9100-4a972b3d3166", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the testRepository repository.
        /// </summary>
        public static testRepository repo = testRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Explorer.List11.List1' at 310;146.", repo.Explorer.List11.List1Info, new RecordItemIndex(0));
            repo.Explorer.List11.List1.Click(System.Windows.Forms.MouseButtons.Right, "310;146");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.MenuItemNew' at 143;6.", repo.Explorer1.MenuItemNewInfo, new RecordItemIndex(1));
            repo.Explorer1.MenuItemNew.Click("143;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer2.TextDocument' at 154;4.", repo.Explorer2.TextDocumentInfo, new RecordItemIndex(2));
            repo.Explorer2.TextDocument.Click("154;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.List11.List1' at 488;334.", repo.Explorer.List11.List1Info, new RecordItemIndex(3));
            repo.Explorer.List11.List1.Click("488;334");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Explorer.List11.NewTextDocument' at 33;41.", repo.Explorer.List11.NewTextDocumentInfo, new RecordItemIndex(4));
            repo.Explorer.List11.NewTextDocument.Click(System.Windows.Forms.MouseButtons.Right, "33;41");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.Delete' at 165;19.", repo.Explorer1.DeleteInfo, new RecordItemIndex(5));
            repo.Explorer1.Delete.Click("165;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Explorer.List11.RecycleBin' at 56;52.", repo.Explorer.List11.RecycleBinInfo, new RecordItemIndex(6));
            repo.Explorer.List11.RecycleBin.Click(System.Windows.Forms.MouseButtons.Right, "56;52");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.List11.RecycleBin' at 49;36.", repo.Explorer.List11.RecycleBinInfo, new RecordItemIndex(7));
            repo.Explorer.List11.RecycleBin.Click("49;36");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Explorer.List11.RecycleBin' at 49;36.", repo.Explorer.List11.RecycleBinInfo, new RecordItemIndex(8));
            repo.Explorer.List11.RecycleBin.Click(System.Windows.Forms.MouseButtons.Right, "49;36");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.EmptyRecycleBin' at 109;5.", repo.Explorer1.EmptyRecycleBinInfo, new RecordItemIndex(9));
            repo.Explorer1.EmptyRecycleBin.Click("109;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=795,Y=448}.", new RecordItemIndex(10));
            Mouse.MoveTo(795, 448);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Explorer.List11.RecycleBin' at 20;41.", repo.Explorer.List11.RecycleBinInfo, new RecordItemIndex(11));
            repo.Explorer.List11.RecycleBin.DoubleClick("20;41");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='This folder is empty.') on item 'RecycleBin.EmptyText'.", repo.RecycleBin.EmptyTextInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.RecycleBin.EmptyTextInfo, "Text", "This folder is empty.");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
